apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: From Template
  namespace: 1000
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: To Yaml File
        name: traefik
      version: 9.18.2
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: NodePort