apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helm-git
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/sridharlreddy/flux-test
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/ 