apiVersion:  helm.toolkit.fluxcd.io/v2beta1 
kind: HelmRelease
metadata:
  name: pxc-db
  namespace: flux-system
spec:
  kubeConfig: 
    secretRef: gke-paas-2
  targetNamespace: pxc-app1
  storageNamespace: pxc-app1
  values:
      size: 3
---
apiVersion: v1
kind: Secret
metadata:
  name: pxc-db-secret
  namespace: flux-system
type: Opaque
data:
  root-password: cm9vdC1wYXNzd29yZA==