apiVersion:  helm.toolkit.fluxcd.io/v2beta1 
kind: HelmRelease
metadata:
  name: gke-paas-2-tenant1-app1-pxc-db # Should be unique across all apps
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: pxc-db
      sourceRef:
        kind: HelmRepository
        name: paas
      version: 0.1.18
      interval: 10m
      valuesFiles:
      - values.yaml
  kubeConfig: 
    secretRef: 
      name: gke-paas-2 # Cluster kubeconfig secret name
  releaseName: pxc-db # Match with app name
  targetNamespace: tenant1 # Set it actual namespace where helm chart needs to be installed
  storageNamespace: tenant1 # Set it actual namespace where helm chart needs to be installed, same as previous
  timeout: 10m0s
  install:
    createNamespace: false
    skipCRDs: false
  valuesFrom:
  - kind: Secret
    name: gke-paas-2-tenant1-pxc-db-secret # Read passwords from secret
    valuesKey: root-password
    targetPath: secrets.passwords.root
  values:
    dbName: pxc-db
    backupFrequency: MW
    haproxy:
      enabled: true
      serviceType: LoadBalancer
    pxc:
      image:
        tag: 8.0.22-13.1
      persistence:
        enabled: true
        size: 1Gi
      resources:
        requests:
          cpu: 400m
          memory: 4G
      sidecarVolumes:
      - name: backup-nfs
        persistentVolumeClaim:
          claimName: pvc-pxc-db
      size: 3
    retention: 1
    schedule: 45 23 1 * *
    scheduleIncremental: 45 23 * * 0
    # secrets: ## secrets should be used for these to store in git
    #   passwords:
    #     root: Db@1234567
    upgradeOptions:
      apply: Disabled
