apiVersion:  helm.toolkit.fluxcd.io/v2beta1 
kind: HelmRelease
metadata:
  name: pxc-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: pxc-operator
      sourceRef:
        kind: HelmRepository
        name: paas
      version: 1.8.0
      interval: 10m
      valuesFiles:
      - values.yaml
  kubeConfig: 
    secretRef: gke-paas-2
  releaseName: pxc-operator
  targetNamespace: pxc
  storageNamespace: pxc
  timeout: 10m0s
  install:
    createNamespace: false
    skipCRDs: false
  values:
    image:
      repository: sridharlreddy/percona-operator
      tag: 1.8.0-v1
